# mongo-express.yml
version: "3"
networks:
  default:
    name: mongo-express-network
    
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    volumes:
      - mongodb-data:/data/db

  mongo-express:
    restart: always
    image: mongo-express
    depends_on: 
      - mongodb
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
      
  node-app:
    restart: always
    image: nirmshah/node-app:latest
    depends_on: 
      - mongodb
    container_name: node-app
    ports:
      - 3000:3000   
    environment:
      - MONGO_DB_USERNAME=rootuser
      - MONGO_DB_PWD=rootpass
      - MONGO_DB_SERVER=mongodb
      
volumes:
  mongodb-data:
    driver: local